const ALL_ROLES_LIST = [
  'FULL_ADMIN',
  'BASIC_ADMIN',
  'CLIENT_ADMIN',
  'CLIENT_USER',
];
const ROLES = ALL_ROLES_LIST.reduce(function(acc, cur) {
  return { ...acc, [cur]: cur };
}, { });

const ALL_ACTIONS_LIST = [
  'READ_CLIENT_PROFILE',
  'WRITE_CLIENT_PROFILE',
  'READ_CLIENT_USER_PROFILE',
  'WRITE_CLIENT_USER_PROFILE',

  'READ_OWN_CLIENT_PROFILE',
  'WRITE_OWN_CLIENT_PROFILE',
  'READ_OWN_CLIENT_USER_PROFILE',
  'WRITE_OWN_CLIENT_USER_PROFILE',

  'READ_OWN_PROFILE',
  'WRITE_OWN_PROFILE',
];
const ACTIONS = ALL_ACTIONS_LIST.reduce(function(acc, cur) {
  return { ...acc, [cur]: cur };
}, { });

const ACTIONS_PER_ROLE = {
  [ROLES.FULL_ADMIN]: Object.keys(ACTIONS).map(k => ACTIONS[k]),
  [ROLES.BASIC_ADMIN]: [
    ACTIONS.READ_CLIENT_PROFILE,
    ACTIONS.READ_CLIENT_USER_PROFILE,
    ACTIONS.READ_OWN_PROFILE,
    ACTIONS.WRITE_OWN_PROFILE,
  ],
  [ROLES.CLIENT_ADMIN]: [
    ACTIONS.READ_OWN_CLIENT_PROFILE,
    ACTIONS.WRITE_OWN_CLIENT_PROFILE,
    ACTIONS.READ_OWN_CLIENT_USER_PROFILE,
    ACTIONS.WRITE_OWN_CLIENT_USER_PROFILE,

    ACTIONS.READ_OWN_PROFILE,
    ACTIONS.WRITE_OWN_PROFILE,
  ],
  [ROLES.CLIENT_USER]: [
    ACTIONS.READ_OWN_PROFILE,
    ACTIONS.WRITE_OWN_PROFILE,
  ],
};

const ACTIONS_REQUIRE_CLIENT_PRIVILEGES = [
  ACTIONS.READ_OWN_CLIENT_PROFILE,
  ACTIONS.WRITE_OWN_CLIENT_PROFILE,
  ACTIONS.READ_OWN_CLIENT_USER_PROFILE,
  ACTIONS.WRITE_OWN_CLIENT_USER_PROFILE,
];

module.exports = {
  ROLES,
  ACTIONS,
  ACTIONS_PER_ROLE,
  ACTIONS_REQUIRE_CLIENT_PRIVILEGES,
};
